// Code generated by qtc from "page.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/page.qtpl:1
package templates

//line templates/page.qtpl:1
import "html/template"

//line templates/page.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/page.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/page.qtpl:4
// PageParams holds all parameters needed for page rendering
type PageParams struct {
	Title          string
	SiteID         int
	AnalyticsCode  string
	BaiduPushJS    string
	ArticleContent string
	Content        string

	// Function providers
	clsFunc     func(string) string
	urlFunc     func() string
	keywordFunc func() string
	imageFunc   func() string
	numberFunc  func(int, int) int
	nowFunc     func() string
}

// NewPageParams creates a new PageParams with function providers
func NewPageParams(
	title string,
	siteID int,
	analyticsCode, baiduPushJS, articleContent, content string,
	clsFunc func(string) string,
	urlFunc func() string,
	keywordFunc func() string,
	imageFunc func() string,
	numberFunc func(int, int) int,
	nowFunc func() string,
) *PageParams {
	return &PageParams{
		Title:          title,
		SiteID:         siteID,
		AnalyticsCode:  analyticsCode,
		BaiduPushJS:    baiduPushJS,
		ArticleContent: articleContent,
		Content:        content,
		clsFunc:        clsFunc,
		urlFunc:        urlFunc,
		keywordFunc:    keywordFunc,
		imageFunc:      imageFunc,
		numberFunc:     numberFunc,
		nowFunc:        nowFunc,
	}
}

// Cls generates random CSS class
func (p *PageParams) Cls(name string) string {
	if p.clsFunc != nil {
		return p.clsFunc(name)
	}
	return name
}

// RandomURL returns a random URL
func (p *PageParams) RandomURL() string {
	if p.urlFunc != nil {
		return p.urlFunc()
	}
	return "/?123456.html"
}

// RandomKeyword returns a random keyword (HTML safe)
func (p *PageParams) RandomKeyword() template.HTML {
	if p.keywordFunc != nil {
		return template.HTML(p.keywordFunc())
	}
	return template.HTML("关键词")
}

// RandomImage returns a random image URL
func (p *PageParams) RandomImage() string {
	if p.imageFunc != nil {
		return p.imageFunc()
	}
	return "/static/images/default.png"
}

// RandomNumber returns a random number in range [min, max]
func (p *PageParams) RandomNumber(min, max int) int {
	if p.numberFunc != nil {
		return p.numberFunc(min, max)
	}
	return min
}

// Now returns current time string
func (p *PageParams) Now() string {
	if p.nowFunc != nil {
		return p.nowFunc()
	}
	return "2024-01-01 00:00:00"
}

//line templates/page.qtpl:99
func (p *PageParams) StreamRender(qw422016 *qt422016.Writer) {
//line templates/page.qtpl:99
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta name="applicable-device" content="pc" />
    <meta http-equiv="Cache-Control" content="no-transform" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <title>`)
//line templates/page.qtpl:109
	qw422016.E().S(p.Title)
//line templates/page.qtpl:109
	qw422016.N().S(`</title>

    <meta http-equiv="mobile-agent" content="format=xhtml; url=`)
//line templates/page.qtpl:111
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:111
	qw422016.N().S(`" />
    <meta http-equiv="mobile-agent" content="format=html5; url=`)
//line templates/page.qtpl:112
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:112
	qw422016.N().S(`" />

    <meta name="keywords" content="" />
    <meta name="description" content="" />

    <link href="http://www.imansoft.cn/static/css/3673.css" type="text/css" rel="stylesheet" />

    <script>
    var _pageinfo = {
        id: "`)
//line templates/page.qtpl:121
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:121
	qw422016.N().S(`",
        path: "down",
        categroyId: '`)
//line templates/page.qtpl:123
	qw422016.N().D(p.RandomNumber(100, 999))
//line templates/page.qtpl:123
	qw422016.N().S(`',
        rootId: '`)
//line templates/page.qtpl:124
	qw422016.N().D(p.RandomNumber(1, 9))
//line templates/page.qtpl:124
	qw422016.N().S(`',
        commendid: '0',
        catalogname: '`)
//line templates/page.qtpl:126
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:126
	qw422016.N().S(`',
        softname: '`)
//line templates/page.qtpl:127
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:127
	qw422016.N().S(`',
        softver: '`)
//line templates/page.qtpl:128
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:128
	qw422016.N().S(`',
        system: '`)
//line templates/page.qtpl:129
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:129
	qw422016.N().S(`',
        softlicence: "`)
//line templates/page.qtpl:130
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:130
	qw422016.N().S(`",
        body: "1"
    }
    </script>
    <script type="text/javascript" src="/static/js/jquerymin.js"></script>
    <script type="text/javascript" src="/static/js/maininfo.js"></script>

    <meta property="og:type" content="soft" />
    <meta property="og:description" content="" />
    <meta property="og:image" content="`)
//line templates/page.qtpl:139
	qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:139
	qw422016.N().S(`" />
    <meta property="og:title" content="`)
//line templates/page.qtpl:140
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:140
	qw422016.N().S(`" />

    <meta property="og:soft:operating_system" content="`)
//line templates/page.qtpl:142
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:142
	qw422016.N().S(`" />
    <meta property="og:soft:language" content="`)
//line templates/page.qtpl:143
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:143
	qw422016.N().S(`" />
    <meta property="og:soft:license" content="`)
//line templates/page.qtpl:144
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:144
	qw422016.N().S(`" />
    <meta property="og:soft:url" content="`)
//line templates/page.qtpl:145
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:145
	qw422016.N().S(`" />
    <meta property="og:release_date" content="`)
//line templates/page.qtpl:146
	qw422016.E().S(p.Now())
//line templates/page.qtpl:146
	qw422016.N().S(`" />

    <meta property="bytedance:published_time" content="`)
//line templates/page.qtpl:148
	qw422016.E().S(p.Now())
//line templates/page.qtpl:148
	qw422016.N().S(`" />
    <meta property="bytedance:lrDate_time" content="`)
//line templates/page.qtpl:149
	qw422016.E().S(p.Now())
//line templates/page.qtpl:149
	qw422016.N().S(`" />
    <meta property="bytedance:updated_time" content="`)
//line templates/page.qtpl:150
	qw422016.E().S(p.Now())
//line templates/page.qtpl:150
	qw422016.N().S(`" />

    `)
//line templates/page.qtpl:152
	qw422016.N().S(p.AnalyticsCode)
//line templates/page.qtpl:152
	qw422016.N().S(`
</head>

<body id="downpage">
    <div class="`)
//line templates/page.qtpl:156
	qw422016.E().S(p.Cls("topper"))
//line templates/page.qtpl:156
	qw422016.N().S(`">
        <div class="`)
//line templates/page.qtpl:157
	qw422016.E().S(p.Cls("box"))
//line templates/page.qtpl:157
	qw422016.N().S(`">
            <span class="`)
//line templates/page.qtpl:158
	qw422016.E().S(p.Cls("fl"))
//line templates/page.qtpl:158
	qw422016.N().S(`">`)
//line templates/page.qtpl:158
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:158
	qw422016.N().S(`</span>
            `)
//line templates/page.qtpl:159
	for i := 0; i < 4; i++ {
//line templates/page.qtpl:159
		qw422016.N().S(`
            <a href="`)
//line templates/page.qtpl:160
		qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:160
		qw422016.N().S(`">`)
//line templates/page.qtpl:160
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:160
		qw422016.N().S(`</a>|
            `)
//line templates/page.qtpl:161
	}
//line templates/page.qtpl:161
	qw422016.N().S(`
        </div>
    </div>

    <div class="`)
//line templates/page.qtpl:165
	qw422016.E().S(p.Cls("header"))
//line templates/page.qtpl:165
	qw422016.N().S(`">
        <div class="`)
//line templates/page.qtpl:166
	qw422016.E().S(p.Cls("box"))
//line templates/page.qtpl:166
	qw422016.N().S(`">
            <div class="`)
//line templates/page.qtpl:167
	qw422016.E().S(p.Cls("logo"))
//line templates/page.qtpl:167
	qw422016.N().S(`">
                <a href="`)
//line templates/page.qtpl:168
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:168
	qw422016.N().S(`"><b>`)
//line templates/page.qtpl:168
	qw422016.N().D(p.SiteID)
//line templates/page.qtpl:168
	qw422016.N().S(`</b>.com</a>
            </div>

            <div class="`)
//line templates/page.qtpl:171
	qw422016.E().S(p.Cls("menu"))
//line templates/page.qtpl:171
	qw422016.N().S(`">
                <a href="`)
//line templates/page.qtpl:172
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:172
	qw422016.N().S(`" class="`)
//line templates/page.qtpl:172
	qw422016.E().S(p.Cls("menuGame"))
//line templates/page.qtpl:172
	qw422016.N().S(`"><i></i>网络游戏</a>
                <a href="`)
//line templates/page.qtpl:173
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:173
	qw422016.N().S(`" class="`)
//line templates/page.qtpl:173
	qw422016.E().S(p.Cls("menuGame"))
//line templates/page.qtpl:173
	qw422016.N().S(`"><i></i>单机游戏</a>
                <a href="`)
//line templates/page.qtpl:174
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:174
	qw422016.N().S(`" class="`)
//line templates/page.qtpl:174
	qw422016.E().S(p.Cls("menuApp"))
//line templates/page.qtpl:174
	qw422016.N().S(`"><i></i>手机应用</a>
                <a href="`)
//line templates/page.qtpl:175
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:175
	qw422016.N().S(`" class="`)
//line templates/page.qtpl:175
	qw422016.E().S(p.Cls("menuTopic"))
//line templates/page.qtpl:175
	qw422016.N().S(`"><i></i>电脑软件</a>
                <a href="`)
//line templates/page.qtpl:176
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:176
	qw422016.N().S(`" class="`)
//line templates/page.qtpl:176
	qw422016.E().S(p.Cls("menuNew"))
//line templates/page.qtpl:176
	qw422016.N().S(`"><i></i>专题</a>
                <a href="`)
//line templates/page.qtpl:177
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:177
	qw422016.N().S(`" class="`)
//line templates/page.qtpl:177
	qw422016.E().S(p.Cls("menuGame"))
//line templates/page.qtpl:177
	qw422016.N().S(`"><i></i>热门排行榜</a>
            </div>

            <div class="`)
//line templates/page.qtpl:180
	qw422016.E().S(p.Cls("searBox"))
//line templates/page.qtpl:180
	qw422016.N().S(`">
                <div class="`)
//line templates/page.qtpl:181
	qw422016.E().S(p.Cls("search"))
//line templates/page.qtpl:181
	qw422016.N().S(`">
                    <input type="text" class="`)
//line templates/page.qtpl:182
	qw422016.E().S(p.Cls("txt_search"))
//line templates/page.qtpl:182
	qw422016.N().S(`" id="words" value="" />
                    <input type="button" class="`)
//line templates/page.qtpl:183
	qw422016.E().S(p.Cls("btn_search"))
//line templates/page.qtpl:183
	qw422016.N().S(`" />
                </div>
                <div class="`)
//line templates/page.qtpl:185
	qw422016.E().S(p.Cls("hot_word"))
//line templates/page.qtpl:185
	qw422016.N().S(`">
                    `)
//line templates/page.qtpl:186
	for i := 0; i < 9; i++ {
//line templates/page.qtpl:186
		qw422016.N().S(`
                    <a href="`)
//line templates/page.qtpl:187
		qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:187
		qw422016.N().S(`" class="`)
//line templates/page.qtpl:187
		qw422016.E().S(p.Cls("bdcs-hot-item"))
//line templates/page.qtpl:187
		qw422016.N().S(`" target="_blank">`)
//line templates/page.qtpl:187
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:187
		qw422016.N().S(`</a>
                    `)
//line templates/page.qtpl:188
	}
//line templates/page.qtpl:188
	qw422016.N().S(`
                </div>
            </div>
        </div>
    </div>

    <div class="`)
//line templates/page.qtpl:194
	qw422016.E().S(p.Cls("box"))
//line templates/page.qtpl:194
	qw422016.N().S(`">
        <p class="`)
//line templates/page.qtpl:195
	qw422016.E().S(p.Cls("pos"))
//line templates/page.qtpl:195
	qw422016.N().S(`">当前位置：
            <a href="`)
//line templates/page.qtpl:196
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:196
	qw422016.N().S(`">`)
//line templates/page.qtpl:196
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:196
	qw422016.N().S(`</a>→
            <a href="`)
//line templates/page.qtpl:197
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:197
	qw422016.N().S(`">`)
//line templates/page.qtpl:197
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:197
	qw422016.N().S(`</a>→
            <a href="`)
//line templates/page.qtpl:198
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:198
	qw422016.N().S(`">`)
//line templates/page.qtpl:198
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:198
	qw422016.N().S(`</a>
            `)
//line templates/page.qtpl:199
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:199
	qw422016.N().S(` 安卓版
        </p>
    </div>

    <div class="`)
//line templates/page.qtpl:203
	qw422016.E().S(p.Cls("box"))
//line templates/page.qtpl:203
	qw422016.N().S(`">
        <div class="`)
//line templates/page.qtpl:204
	qw422016.E().S(p.Cls("infoSub"))
//line templates/page.qtpl:204
	qw422016.N().S(`">
            <div class="`)
//line templates/page.qtpl:205
	qw422016.E().S(p.Cls("subAppicon"))
//line templates/page.qtpl:205
	qw422016.N().S(`">
                <img src="`)
//line templates/page.qtpl:206
	qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:206
	qw422016.N().S(`" alt="`)
//line templates/page.qtpl:206
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:206
	qw422016.N().S(`" />
                <h1>`)
//line templates/page.qtpl:207
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:207
	qw422016.N().S(`</h1>

                <ul id="dbtns">
                    <li class="`)
//line templates/page.qtpl:210
	qw422016.E().S(p.Cls("az"))
//line templates/page.qtpl:210
	qw422016.N().S(`" id="azbtn">
                        <a href="`)
//line templates/page.qtpl:211
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:211
	qw422016.N().S(`" rel="nofollow" class="`)
//line templates/page.qtpl:211
	qw422016.E().S(p.Cls("down_counter"))
//line templates/page.qtpl:211
	qw422016.N().S(`" id="`)
//line templates/page.qtpl:211
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:211
	qw422016.N().S(`" target="_blank">安卓版下载</a>
                    </li>
                    <li id="pgbtn" class="`)
//line templates/page.qtpl:213
	qw422016.E().S(p.Cls("appstore"))
//line templates/page.qtpl:213
	qw422016.N().S(`">
                        <a target="_blank" id="`)
//line templates/page.qtpl:214
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:214
	qw422016.N().S(`" href="`)
//line templates/page.qtpl:214
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:214
	qw422016.N().S(`">电脑版下载</a>
                    </li>
                </ul>
            </div>

            <ul class="`)
//line templates/page.qtpl:219
	qw422016.E().S(p.Cls("aztop"))
//line templates/page.qtpl:219
	qw422016.N().S(`">
                <li id="showding">
                    <em class="`)
//line templates/page.qtpl:221
	qw422016.E().S(p.Cls("showDinNum"))
//line templates/page.qtpl:221
	qw422016.N().S(`">`)
//line templates/page.qtpl:221
	qw422016.N().D(p.RandomNumber(1, 20))
//line templates/page.qtpl:221
	qw422016.N().S(`</em>
                </li>
                <li id="showcai">
                    <em class="`)
//line templates/page.qtpl:224
	qw422016.E().S(p.Cls("showDinNum"))
//line templates/page.qtpl:224
	qw422016.N().S(`">`)
//line templates/page.qtpl:224
	qw422016.N().D(p.RandomNumber(1, 10))
//line templates/page.qtpl:224
	qw422016.N().S(`</em>
                </li>
            </ul>

            <div class="`)
//line templates/page.qtpl:228
	qw422016.E().S(p.Cls("subList"))
//line templates/page.qtpl:228
	qw422016.N().S(`">
                <div class="`)
//line templates/page.qtpl:229
	qw422016.E().S(p.Cls("tit"))
//line templates/page.qtpl:229
	qw422016.N().S(`" id="anchorLike">相关推荐</div>
                <ul class="`)
//line templates/page.qtpl:230
	qw422016.E().S(p.Cls("zolSub"))
//line templates/page.qtpl:230
	qw422016.N().S(`">
                    `)
//line templates/page.qtpl:231
	for i := 0; i < 50; i++ {
//line templates/page.qtpl:231
		qw422016.N().S(`
                    <li>
                        <a href="`)
//line templates/page.qtpl:233
		qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:233
		qw422016.N().S(`" title="`)
//line templates/page.qtpl:233
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:233
		qw422016.N().S(`">
                            <img src="`)
//line templates/page.qtpl:234
		qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:234
		qw422016.N().S(`" alt="`)
//line templates/page.qtpl:234
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:234
		qw422016.N().S(`" />
                            <section>
                                <h3>`)
//line templates/page.qtpl:236
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:236
		qw422016.N().S(`</h3>
                                <span class="`)
//line templates/page.qtpl:237
		qw422016.E().S(p.Cls("star"))
//line templates/page.qtpl:237
		qw422016.N().S(`" title="热度评级：6/10">
                                    <span style="width:calc(40%*2)"></span>
                                </span>
                                <p>v`)
//line templates/page.qtpl:240
		qw422016.N().D(p.RandomNumber(1, 9))
//line templates/page.qtpl:240
		qw422016.N().S(`.`)
//line templates/page.qtpl:240
		qw422016.N().D(p.RandomNumber(0, 9))
//line templates/page.qtpl:240
		qw422016.N().S(`.`)
//line templates/page.qtpl:240
		qw422016.N().D(p.RandomNumber(0, 99))
//line templates/page.qtpl:240
		qw422016.N().S(`</p>
                            </section>
                        </a>
                    </li>
                    `)
//line templates/page.qtpl:244
	}
//line templates/page.qtpl:244
	qw422016.N().S(`
                </ul>
            </div>
        </div>

        <div class="`)
//line templates/page.qtpl:249
	qw422016.E().S(p.Cls("infoRight"))
//line templates/page.qtpl:249
	qw422016.N().S(`">
            <dl class="`)
//line templates/page.qtpl:250
	qw422016.E().S(p.Cls("kbox"))
//line templates/page.qtpl:250
	qw422016.N().S(`">
                <dt>相关游戏</dt>
                <dd>
                    `)
//line templates/page.qtpl:253
	for i := 0; i < 18; i++ {
//line templates/page.qtpl:253
		qw422016.N().S(`
                    <a href="`)
//line templates/page.qtpl:254
		qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:254
		qw422016.N().S(`">
                        <img alt="`)
//line templates/page.qtpl:255
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:255
		qw422016.N().S(`" src="`)
//line templates/page.qtpl:255
		qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:255
		qw422016.N().S(`" />
                        <i>`)
//line templates/page.qtpl:256
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:256
		qw422016.N().S(`</i>
                    </a>
                    `)
//line templates/page.qtpl:258
	}
//line templates/page.qtpl:258
	qw422016.N().S(`
                </dd>
            </dl>

            <div class="`)
//line templates/page.qtpl:262
	qw422016.E().S(p.Cls("tit"))
//line templates/page.qtpl:262
	qw422016.N().S(`">热门冒险解谜</div>
            <ul class="`)
//line templates/page.qtpl:263
	qw422016.E().S(p.Cls("topList"))
//line templates/page.qtpl:263
	qw422016.N().S(`">
                `)
//line templates/page.qtpl:264
	for i := 0; i < 400; i++ {
//line templates/page.qtpl:264
		qw422016.N().S(`
                <li>
                    <i>`)
//line templates/page.qtpl:266
		qw422016.E().S(p.Now())
//line templates/page.qtpl:266
		qw422016.N().S(`</i>
                    <b class='on'>`)
//line templates/page.qtpl:267
		qw422016.N().D(p.RandomNumber(100, 999))
//line templates/page.qtpl:267
		qw422016.N().S(`</b>
                    <a href="`)
//line templates/page.qtpl:268
		qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:268
		qw422016.N().S(`" target="_blank">
                        <img src="`)
//line templates/page.qtpl:269
		qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:269
		qw422016.N().S(`" alt="`)
//line templates/page.qtpl:269
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:269
		qw422016.N().S(`" />
                    </a>
                    <p><a href="`)
//line templates/page.qtpl:271
		qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:271
		qw422016.N().S(`" target="_blank">`)
//line templates/page.qtpl:271
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:271
		qw422016.N().S(`</a></p>
                </li>
                `)
//line templates/page.qtpl:273
	}
//line templates/page.qtpl:273
	qw422016.N().S(`
            </ul>
        </div>

        <div class="`)
//line templates/page.qtpl:277
	qw422016.E().S(p.Cls("infoMain"))
//line templates/page.qtpl:277
	qw422016.N().S(`">
            <table cellpadding="0" cellspacing="0">
                <tr>
                    <td><i>分类：</i>`)
//line templates/page.qtpl:280
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:280
	qw422016.N().S(` / `)
//line templates/page.qtpl:280
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:280
	qw422016.N().S(`</td>
                    <td><i>大小：</i></td>
                    <td><i>授权：</i>`)
//line templates/page.qtpl:282
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:282
	qw422016.N().S(`</td>
                </tr>
                <tr>
                    <td><i>语言：</i>`)
//line templates/page.qtpl:285
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:285
	qw422016.N().S(`</td>
                    <td><i>更新：</i>`)
//line templates/page.qtpl:286
	qw422016.E().S(p.Now())
//line templates/page.qtpl:286
	qw422016.N().S(`</td>
                    <td><i>等级：</i>
                        <span class="`)
//line templates/page.qtpl:288
	qw422016.E().S(p.Cls("star"))
//line templates/page.qtpl:288
	qw422016.N().S(`">
                            <span style="width:calc(40%*2)"></span>
                        </span>
                    </td>
                </tr>
                <tr>
                    <td><i>平台：</i>`)
//line templates/page.qtpl:294
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:294
	qw422016.N().S(`</td>
                    <td><i>厂商：</i>
                        <a href="`)
//line templates/page.qtpl:296
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:296
	qw422016.N().S(`" target="_blank">`)
//line templates/page.qtpl:296
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:296
	qw422016.N().S(`</a>
                    </td>
                    <td class="`)
//line templates/page.qtpl:298
	qw422016.E().S(p.Cls("siteurl"))
//line templates/page.qtpl:298
	qw422016.N().S(`"><i>官网：</i>暂无</td>
                </tr>
                <tr>
                    <td class="`)
//line templates/page.qtpl:301
	qw422016.E().S(p.Cls("qx"))
//line templates/page.qtpl:301
	qw422016.N().S(`"><i>权限：</i><b>查看</b>
                        <div class="`)
//line templates/page.qtpl:302
	qw422016.E().S(p.Cls("qxstr"))
//line templates/page.qtpl:302
	qw422016.N().S(`">允许程序访问网络.</div>
                    </td>
                    <td class="`)
//line templates/page.qtpl:304
	qw422016.E().S(p.Cls("beian"))
//line templates/page.qtpl:304
	qw422016.N().S(`"><i>备案：</i>湘ICP备2023018554号-3A</td>
                    <td></td>
                </tr>
                <tr>
                    <td colspan="3"><i>标签：</i>
                        <span class="`)
//line templates/page.qtpl:309
	qw422016.E().S(p.Cls("tipWord"))
//line templates/page.qtpl:309
	qw422016.N().S(`">
                            `)
//line templates/page.qtpl:310
	for i := 0; i < 3; i++ {
//line templates/page.qtpl:310
		qw422016.N().S(`
                            <a href="`)
//line templates/page.qtpl:311
		qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:311
		qw422016.N().S(`" target="_blank">`)
//line templates/page.qtpl:311
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:311
		qw422016.N().S(`</a>
                            `)
//line templates/page.qtpl:312
	}
//line templates/page.qtpl:312
	qw422016.N().S(`
                        </span>
                    </td>
                </tr>
            </table>

            <dl class="`)
//line templates/page.qtpl:318
	qw422016.E().S(p.Cls("queTit"))
//line templates/page.qtpl:318
	qw422016.N().S(`">
                <dd class="`)
//line templates/page.qtpl:319
	qw422016.E().S(p.Cls("on"))
//line templates/page.qtpl:319
	qw422016.N().S(`"><i class="`)
//line templates/page.qtpl:319
	qw422016.E().S(p.Cls("queTop"))
//line templates/page.qtpl:319
	qw422016.N().S(`"></i>详情</dd>
                <dd><i class="`)
//line templates/page.qtpl:320
	qw422016.E().S(p.Cls("queInfo"))
//line templates/page.qtpl:320
	qw422016.N().S(`"></i>介绍</dd>
                <dd><i class="`)
//line templates/page.qtpl:321
	qw422016.E().S(p.Cls("queLike"))
//line templates/page.qtpl:321
	qw422016.N().S(`"></i>猜你喜欢</dd>
                <dd><i class="`)
//line templates/page.qtpl:322
	qw422016.E().S(p.Cls("queHistory"))
//line templates/page.qtpl:322
	qw422016.N().S(`"></i>相关版本</dd>
            </dl>

            <div class="`)
//line templates/page.qtpl:325
	qw422016.E().S(p.Cls("appWrap"))
//line templates/page.qtpl:325
	qw422016.N().S(`" id="div_screenshots">
                <h3><i class="`)
//line templates/page.qtpl:326
	qw422016.E().S(p.Cls("iInfo"))
//line templates/page.qtpl:326
	qw422016.N().S(`"></i>截图</h3>
                <div class="`)
//line templates/page.qtpl:327
	qw422016.E().S(p.Cls("infopic"))
//line templates/page.qtpl:327
	qw422016.N().S(`" id="div_screenshots2">
                    <div class="`)
//line templates/page.qtpl:328
	qw422016.E().S(p.Cls("picbox"))
//line templates/page.qtpl:328
	qw422016.N().S(`">
                        <ul class="`)
//line templates/page.qtpl:329
	qw422016.E().S(p.Cls("piclist"))
//line templates/page.qtpl:329
	qw422016.N().S(`">
                            `)
//line templates/page.qtpl:330
	for i := 0; i < 4; i++ {
//line templates/page.qtpl:330
		qw422016.N().S(`
                            <li>
                                <a href="`)
//line templates/page.qtpl:332
		qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:332
		qw422016.N().S(`" data-lightbox="s1" data-text="`)
//line templates/page.qtpl:332
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:332
		qw422016.N().S(`">
                                    <img src="`)
//line templates/page.qtpl:333
		qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:333
		qw422016.N().S(`" alt="`)
//line templates/page.qtpl:333
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:333
		qw422016.N().S(`" />
                                </a>
                            </li>
                            `)
//line templates/page.qtpl:336
	}
//line templates/page.qtpl:336
	qw422016.N().S(`
                        </ul>
                    </div>
                    <div class="`)
//line templates/page.qtpl:339
	qw422016.E().S(p.Cls("gn_prev"))
//line templates/page.qtpl:339
	qw422016.N().S(`"></div>
                    <div class="`)
//line templates/page.qtpl:340
	qw422016.E().S(p.Cls("gn_next"))
//line templates/page.qtpl:340
	qw422016.N().S(`"></div>
                </div>
            </div>

            <div class="`)
//line templates/page.qtpl:344
	qw422016.E().S(p.Cls("appWrap"))
//line templates/page.qtpl:344
	qw422016.N().S(`">
                <h3 id="anchorInfo"><i class="`)
//line templates/page.qtpl:345
	qw422016.E().S(p.Cls("iInfo"))
//line templates/page.qtpl:345
	qw422016.N().S(`"></i>内容详情</h3>
                <div class="`)
//line templates/page.qtpl:346
	qw422016.E().S(p.Cls("txtIntro"))
//line templates/page.qtpl:346
	qw422016.N().S(`">
                    <p id="news_1">`)
//line templates/page.qtpl:347
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:347
	qw422016.N().S(`</p>
                    <p id="news_2">`)
//line templates/page.qtpl:348
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:348
	qw422016.N().S(`</p>
                    <p id="news_3">`)
//line templates/page.qtpl:349
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:349
	qw422016.N().S(`</p>

                    <p style="text-indent:2em;">
                        <i>厂商新闻</i>`)
//line templates/page.qtpl:352
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:352
	qw422016.N().S(` 时间：`)
//line templates/page.qtpl:352
	qw422016.E().S(p.Now())
//line templates/page.qtpl:352
	qw422016.N().S(`
                    </p>

                    <ul class="`)
//line templates/page.qtpl:355
	qw422016.E().S(p.Cls("intem"))
//line templates/page.qtpl:355
	qw422016.N().S(`">
                        <ul class="`)
//line templates/page.qtpl:356
	qw422016.E().S(p.Cls("intem"))
//line templates/page.qtpl:356
	qw422016.N().S(`">
                            <li>编辑：admin</li>
                        </ul>
                        <p align="center">`)
//line templates/page.qtpl:359
	qw422016.E().S(p.Now())
//line templates/page.qtpl:359
	qw422016.N().S(`
                        <div class="`)
//line templates/page.qtpl:360
	qw422016.E().S(p.Cls("left_zw"))
//line templates/page.qtpl:360
	qw422016.N().S(`">
                            <p>　`)
//line templates/page.qtpl:361
	qw422016.N().S(p.Content)
//line templates/page.qtpl:361
	qw422016.N().S(`</p>

                            <table border="0" cellspacing="0" cellpadding="0" align="left" class="`)
//line templates/page.qtpl:363
	qw422016.E().S(p.Cls("adInContent"))
//line templates/page.qtpl:363
	qw422016.N().S(`">
                                <tr>
                                    <td></td>
                                </tr>
                            </table>

                            <div class="`)
//line templates/page.qtpl:369
	qw422016.E().S(p.Cls("adEditor"))
//line templates/page.qtpl:369
	qw422016.N().S(`">
                                <div class="`)
//line templates/page.qtpl:370
	qw422016.E().S(p.Cls("left_name"))
//line templates/page.qtpl:370
	qw422016.N().S(` right">
                                    <span>编辑：站点编辑</span>
                                </div>
                            </div>
                            <div id="function_code_page"></div>
                        </div>
                        <img src="`)
//line templates/page.qtpl:376
	qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:376
	qw422016.N().S(`" alt="" />
                        </p>
                    </ul>
                </div>
            </div>

            <div class="`)
//line templates/page.qtpl:382
	qw422016.E().S(p.Cls("appWrap"))
//line templates/page.qtpl:382
	qw422016.N().S(`"></div>

            <div class="`)
//line templates/page.qtpl:384
	qw422016.E().S(p.Cls("company"))
//line templates/page.qtpl:384
	qw422016.N().S(`" id="company">
                <p class="`)
//line templates/page.qtpl:385
	qw422016.E().S(p.Cls("introTit"))
//line templates/page.qtpl:385
	qw422016.N().S(`">厂商其他下载</p>
                <p class="`)
//line templates/page.qtpl:386
	qw422016.E().S(p.Cls("sys"))
//line templates/page.qtpl:386
	qw422016.N().S(`">
                    <span>安卓应用</span>
                    <span>安卓手游</span>
                    <span>苹果应用</span>
                    <span>苹果手游</span>
                    <span>电脑</span>
                    <a href="`)
//line templates/page.qtpl:392
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:392
	qw422016.N().S(`" target="_blank">更多+</a>
                </p>
                <ul class="`)
//line templates/page.qtpl:394
	qw422016.E().S(p.Cls("clearfix"))
//line templates/page.qtpl:394
	qw422016.N().S(`"></ul>
                <ul class="`)
//line templates/page.qtpl:395
	qw422016.E().S(p.Cls("clearfix"))
//line templates/page.qtpl:395
	qw422016.N().S(`">
                    `)
//line templates/page.qtpl:396
	for i := 0; i < 147; i++ {
//line templates/page.qtpl:396
		qw422016.N().S(`
                    <li>
                        <a href="`)
//line templates/page.qtpl:398
		qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:398
		qw422016.N().S(`" target="_blank">
                            <img alt="`)
//line templates/page.qtpl:399
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:399
		qw422016.N().S(`" src="`)
//line templates/page.qtpl:399
		qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:399
		qw422016.N().S(`" />
                            `)
//line templates/page.qtpl:400
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:400
		qw422016.N().S(`
                        </a>
                    </li>
                    `)
//line templates/page.qtpl:403
	}
//line templates/page.qtpl:403
	qw422016.N().S(`
                </ul>
            </div>
        </div>

        <div class="`)
//line templates/page.qtpl:408
	qw422016.E().S(p.Cls("AppBox"))
//line templates/page.qtpl:408
	qw422016.N().S(`">
            <div class="`)
//line templates/page.qtpl:409
	qw422016.E().S(p.Cls("App-details"))
//line templates/page.qtpl:409
	qw422016.N().S(`">
                <img class="`)
//line templates/page.qtpl:410
	qw422016.E().S(p.Cls("icon"))
//line templates/page.qtpl:410
	qw422016.N().S(`" height="51px" width="51px" alt="`)
//line templates/page.qtpl:410
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:410
	qw422016.N().S(`" src="`)
//line templates/page.qtpl:410
	qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:410
	qw422016.N().S(`" />
                <div class="`)
//line templates/page.qtpl:411
	qw422016.E().S(p.Cls("App-details-det"))
//line templates/page.qtpl:411
	qw422016.N().S(`">
                    <div class="`)
//line templates/page.qtpl:412
	qw422016.E().S(p.Cls("app-details-appname"))
//line templates/page.qtpl:412
	qw422016.N().S(`">
                        <h1>`)
//line templates/page.qtpl:413
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:413
	qw422016.N().S(`</h1>
                    </div>
                    <div class="`)
//line templates/page.qtpl:415
	qw422016.E().S(p.Cls("app-details-appdes"))
//line templates/page.qtpl:415
	qw422016.N().S(`">
                        <h3>「活动」首次登录送`)
//line templates/page.qtpl:416
	qw422016.N().D(p.RandomNumber(50, 200))
//line templates/page.qtpl:416
	qw422016.N().S(`元红包</h3>
                    </div>
                    <div class="`)
//line templates/page.qtpl:418
	qw422016.E().S(p.Cls("app-details-appinfo"))
//line templates/page.qtpl:418
	qw422016.N().S(`">
                        <div>`)
//line templates/page.qtpl:419
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:419
	qw422016.N().S(`</div>
                        <div>`)
//line templates/page.qtpl:420
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:420
	qw422016.N().S(`</div>
                    </div>
                </div>
            </div>

            <div class="`)
//line templates/page.qtpl:425
	qw422016.E().S(p.Cls("App-display-a"))
//line templates/page.qtpl:425
	qw422016.N().S(`">
                <div class="`)
//line templates/page.qtpl:426
	qw422016.E().S(p.Cls("download_btn_col"))
//line templates/page.qtpl:426
	qw422016.N().S(`">
                    <a class="`)
//line templates/page.qtpl:427
	qw422016.E().S(p.Cls("normal-down-btn"))
//line templates/page.qtpl:427
	qw422016.N().S(`" href="`)
//line templates/page.qtpl:427
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:427
	qw422016.N().S(`">下载APK</a>
                    <a class="`)
//line templates/page.qtpl:428
	qw422016.E().S(p.Cls("high-speed-down-btn"))
//line templates/page.qtpl:428
	qw422016.N().S(`" href="`)
//line templates/page.qtpl:428
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:428
	qw422016.N().S(`">高速下载</a>
                </div>
                <div class="`)
//line templates/page.qtpl:430
	qw422016.E().S(p.Cls("b-text"))
//line templates/page.qtpl:430
	qw422016.N().S(`">
                    <span class="`)
//line templates/page.qtpl:431
	qw422016.E().S(p.Cls("span"))
//line templates/page.qtpl:431
	qw422016.N().S(`">下载安装你想要的应用 更方便 更快捷 发现更多</span>
                </div>
            </div>

            <div class="`)
//line templates/page.qtpl:435
	qw422016.E().S(p.Cls("App_Hots"))
//line templates/page.qtpl:435
	qw422016.N().S(`">
                <div>
                    <div class="`)
//line templates/page.qtpl:437
	qw422016.E().S(p.Cls("fr"))
//line templates/page.qtpl:437
	qw422016.N().S(`">
                        <img alt="喜欢" src="/static/images/icon_03.png" />
                        <span>`)
//line templates/page.qtpl:439
	qw422016.N().D(p.RandomNumber(30, 90))
//line templates/page.qtpl:439
	qw422016.N().S(`%好评(`)
//line templates/page.qtpl:439
	qw422016.N().D(p.RandomNumber(10, 100))
//line templates/page.qtpl:439
	qw422016.N().S(`人)</span>
                    </div>
                </div>
                <div>
                    <div class="`)
//line templates/page.qtpl:443
	qw422016.E().S(p.Cls("fl"))
//line templates/page.qtpl:443
	qw422016.N().S(`">
                        <img alt="评论" src="/static/images/icon_04.png" />
                        <span>`)
//line templates/page.qtpl:445
	qw422016.N().D(p.RandomNumber(10, 200))
//line templates/page.qtpl:445
	qw422016.N().S(`</span>
                    </div>
                </div>
            </div>

            <div class="`)
//line templates/page.qtpl:450
	qw422016.E().S(p.Cls("img"))
//line templates/page.qtpl:450
	qw422016.N().S(`">
                <div class="`)
//line templates/page.qtpl:451
	qw422016.E().S(p.Cls("App_ImgBox"))
//line templates/page.qtpl:451
	qw422016.N().S(`">
                    `)
//line templates/page.qtpl:452
	for i := 0; i < 5; i++ {
//line templates/page.qtpl:452
		qw422016.N().S(`
                    <img alt="`)
//line templates/page.qtpl:453
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:453
		qw422016.N().S(`截图`)
//line templates/page.qtpl:453
		qw422016.N().D(i)
//line templates/page.qtpl:453
		qw422016.N().S(`" src="`)
//line templates/page.qtpl:453
		qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:453
		qw422016.N().S(`" />
                    `)
//line templates/page.qtpl:454
	}
//line templates/page.qtpl:454
	qw422016.N().S(`
                </div>
            </div>

            <div class="`)
//line templates/page.qtpl:458
	qw422016.E().S(p.Cls("App_Category"))
//line templates/page.qtpl:458
	qw422016.N().S(`">
                <div class="`)
//line templates/page.qtpl:459
	qw422016.E().S(p.Cls("App_SpreadBox"))
//line templates/page.qtpl:459
	qw422016.N().S(`">
                    <div class="`)
//line templates/page.qtpl:460
	qw422016.E().S(p.Cls("App_SpreadTitle"))
//line templates/page.qtpl:460
	qw422016.N().S(`">
                        <span>详细信息</span>
                        <div class="`)
//line templates/page.qtpl:462
	qw422016.E().S(p.Cls("icon"))
//line templates/page.qtpl:462
	qw422016.N().S(`"></div>
                    </div>
                    <ul class="`)
//line templates/page.qtpl:464
	qw422016.E().S(p.Cls("App_SpreadContent"))
//line templates/page.qtpl:464
	qw422016.N().S(`">
                        <li class="`)
//line templates/page.qtpl:465
	qw422016.E().S(p.Cls("3ce690"))
//line templates/page.qtpl:465
	qw422016.N().S(`">
                            <span class="`)
//line templates/page.qtpl:466
	qw422016.E().S(p.Cls("fl"))
//line templates/page.qtpl:466
	qw422016.N().S(`">软件大小:</span>
                            <span class="`)
//line templates/page.qtpl:467
	qw422016.E().S(p.Cls("fl"))
//line templates/page.qtpl:467
	qw422016.N().S(`">`)
//line templates/page.qtpl:467
	qw422016.N().D(p.RandomNumber(10, 200))
//line templates/page.qtpl:467
	qw422016.N().S(`.`)
//line templates/page.qtpl:467
	qw422016.N().D(p.RandomNumber(10, 99))
//line templates/page.qtpl:467
	qw422016.N().S(`MB</span>
                        </li>
                        <li class="`)
//line templates/page.qtpl:469
	qw422016.E().S(p.Cls("3ce690"))
//line templates/page.qtpl:469
	qw422016.N().S(`">
                            <span class="`)
//line templates/page.qtpl:470
	qw422016.E().S(p.Cls("fl"))
//line templates/page.qtpl:470
	qw422016.N().S(`">最后更新:</span>
                            <span class="`)
//line templates/page.qtpl:471
	qw422016.E().S(p.Cls("fl"))
//line templates/page.qtpl:471
	qw422016.N().S(`">`)
//line templates/page.qtpl:471
	qw422016.E().S(p.Now())
//line templates/page.qtpl:471
	qw422016.N().S(`</span>
                        </li>
                        <li class="`)
//line templates/page.qtpl:473
	qw422016.E().S(p.Cls("3ce690"))
//line templates/page.qtpl:473
	qw422016.N().S(`">
                            <span class="`)
//line templates/page.qtpl:474
	qw422016.E().S(p.Cls("fl"))
//line templates/page.qtpl:474
	qw422016.N().S(`">最新版本:</span>
                            <span class="`)
//line templates/page.qtpl:475
	qw422016.E().S(p.Cls("fl"))
//line templates/page.qtpl:475
	qw422016.N().S(`">V`)
//line templates/page.qtpl:475
	qw422016.N().D(p.RandomNumber(1, 20))
//line templates/page.qtpl:475
	qw422016.N().S(`.`)
//line templates/page.qtpl:475
	qw422016.N().D(p.RandomNumber(0, 99))
//line templates/page.qtpl:475
	qw422016.N().S(`.`)
//line templates/page.qtpl:475
	qw422016.N().D(p.RandomNumber(0, 99))
//line templates/page.qtpl:475
	qw422016.N().S(`</span>
                        </li>
                        <li class="`)
//line templates/page.qtpl:477
	qw422016.E().S(p.Cls("3ce690"))
//line templates/page.qtpl:477
	qw422016.N().S(`">
                            <span class="`)
//line templates/page.qtpl:478
	qw422016.E().S(p.Cls("fl"))
//line templates/page.qtpl:478
	qw422016.N().S(`">文件格式:</span>
                            <span class="`)
//line templates/page.qtpl:479
	qw422016.E().S(p.Cls("fl"))
//line templates/page.qtpl:479
	qw422016.N().S(`">apk</span>
                        </li>
                        <li class="`)
//line templates/page.qtpl:481
	qw422016.E().S(p.Cls("3ce690"))
//line templates/page.qtpl:481
	qw422016.N().S(`">
                            <span class="`)
//line templates/page.qtpl:482
	qw422016.E().S(p.Cls("fl"))
//line templates/page.qtpl:482
	qw422016.N().S(`">应用分类:</span>
                            <span class="`)
//line templates/page.qtpl:483
	qw422016.E().S(p.Cls("fl"))
//line templates/page.qtpl:483
	qw422016.N().S(`">ios-Android</span>
                        </li>
                        <li class="`)
//line templates/page.qtpl:485
	qw422016.E().S(p.Cls("3ce690"))
//line templates/page.qtpl:485
	qw422016.N().S(`">
                            <span class="`)
//line templates/page.qtpl:486
	qw422016.E().S(p.Cls("fl"))
//line templates/page.qtpl:486
	qw422016.N().S(`">使用语言:</span>
                            <span class="`)
//line templates/page.qtpl:487
	qw422016.E().S(p.Cls("fl"))
//line templates/page.qtpl:487
	qw422016.N().S(`">中文</span>
                        </li>
                        <li class="`)
//line templates/page.qtpl:489
	qw422016.E().S(p.Cls("3ce690"))
//line templates/page.qtpl:489
	qw422016.N().S(`">
                            <span class="`)
//line templates/page.qtpl:490
	qw422016.E().S(p.Cls("fl"))
//line templates/page.qtpl:490
	qw422016.N().S(`">:</span>
                            <span class="`)
//line templates/page.qtpl:491
	qw422016.E().S(p.Cls("fl"))
//line templates/page.qtpl:491
	qw422016.N().S(`">需要联网</span>
                        </li>
                        <li class="`)
//line templates/page.qtpl:493
	qw422016.E().S(p.Cls("3ce690"))
//line templates/page.qtpl:493
	qw422016.N().S(`">
                            <span class="`)
//line templates/page.qtpl:494
	qw422016.E().S(p.Cls("fl"))
//line templates/page.qtpl:494
	qw422016.N().S(`">系统要求:</span>
                            <span class="`)
//line templates/page.qtpl:495
	qw422016.E().S(p.Cls("fl"))
//line templates/page.qtpl:495
	qw422016.N().S(`">`)
//line templates/page.qtpl:495
	qw422016.N().D(p.RandomNumber(5, 10))
//line templates/page.qtpl:495
	qw422016.N().S(`.`)
//line templates/page.qtpl:495
	qw422016.N().D(p.RandomNumber(0, 9))
//line templates/page.qtpl:495
	qw422016.N().S(`以上</span>
                        </li>
                    </ul>
                </div>

                <div class="`)
//line templates/page.qtpl:500
	qw422016.E().S(p.Cls("App_SpreadBox"))
//line templates/page.qtpl:500
	qw422016.N().S(`">
                    <div class="`)
//line templates/page.qtpl:501
	qw422016.E().S(p.Cls("App_SpreadTitle"))
//line templates/page.qtpl:501
	qw422016.N().S(`">
                        <span>简介</span>
                        <div class="`)
//line templates/page.qtpl:503
	qw422016.E().S(p.Cls("icon"))
//line templates/page.qtpl:503
	qw422016.N().S(`"></div>
                    </div>
                    <div class="`)
//line templates/page.qtpl:505
	qw422016.E().S(p.Cls("App_Introduce"))
//line templates/page.qtpl:505
	qw422016.N().S(`">
                        <span><a href='`)
//line templates/page.qtpl:506
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:506
	qw422016.N().S(`'>`)
//line templates/page.qtpl:506
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:506
	qw422016.N().S(`</a></span>
                    </div>
                </div>

                <div class="`)
//line templates/page.qtpl:510
	qw422016.E().S(p.Cls("App_SpreadBox"))
//line templates/page.qtpl:510
	qw422016.N().S(`">
                    <div class="`)
//line templates/page.qtpl:511
	qw422016.E().S(p.Cls("App_SpreadTitle"))
//line templates/page.qtpl:511
	qw422016.N().S(`">
                        <span>更新</span>
                        <div class="`)
//line templates/page.qtpl:513
	qw422016.E().S(p.Cls("icon"))
//line templates/page.qtpl:513
	qw422016.N().S(`"></div>
                    </div>
                    <div class="`)
//line templates/page.qtpl:515
	qw422016.E().S(p.Cls("App_Update"))
//line templates/page.qtpl:515
	qw422016.N().S(`">
                        <span>V`)
//line templates/page.qtpl:516
	qw422016.N().D(p.RandomNumber(10, 20))
//line templates/page.qtpl:516
	qw422016.N().S(`.`)
//line templates/page.qtpl:516
	qw422016.N().D(p.RandomNumber(0, 99))
//line templates/page.qtpl:516
	qw422016.N().S(`.`)
//line templates/page.qtpl:516
	qw422016.N().D(p.RandomNumber(0, 9))
//line templates/page.qtpl:516
	qw422016.N().S(`</span>
                        <div class="`)
//line templates/page.qtpl:517
	qw422016.E().S(p.Cls("get_more"))
//line templates/page.qtpl:517
	qw422016.N().S(`">更多历史版本</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="`)
//line templates/page.qtpl:524
	qw422016.E().S(p.Cls("App_SpreadBox"))
//line templates/page.qtpl:524
	qw422016.N().S(`">
        <div class="`)
//line templates/page.qtpl:525
	qw422016.E().S(p.Cls("App_SpreadTitle"))
//line templates/page.qtpl:525
	qw422016.N().S(`">
            <span>相关攻略</span>
            <div class="`)
//line templates/page.qtpl:527
	qw422016.E().S(p.Cls("icon"))
//line templates/page.qtpl:527
	qw422016.N().S(`"></div>
        </div>
        <div class="`)
//line templates/page.qtpl:529
	qw422016.E().S(p.Cls("App_SpreadContent"))
//line templates/page.qtpl:529
	qw422016.N().S(`">
            <ul>
                `)
//line templates/page.qtpl:531
	for i := 0; i < 22; i++ {
//line templates/page.qtpl:531
		qw422016.N().S(`
                <li class="`)
//line templates/page.qtpl:532
		qw422016.E().S(p.Cls("StrategyList_Content"))
//line templates/page.qtpl:532
		qw422016.N().S(`">
                    <div class="`)
//line templates/page.qtpl:533
		qw422016.E().S(p.Cls("StrategyList_ContentTitle ml0"))
//line templates/page.qtpl:533
		qw422016.N().S(`">
                        <a href="`)
//line templates/page.qtpl:534
		qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:534
		qw422016.N().S(`">
                            <div>`)
//line templates/page.qtpl:535
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:535
		qw422016.N().S(`</div>
                        </a>
                    </div>
                    <div class="`)
//line templates/page.qtpl:538
		qw422016.E().S(p.Cls("StrategyList_TimeBox"))
//line templates/page.qtpl:538
		qw422016.N().S(`">
                        <span style="line-height: 40px;">`)
//line templates/page.qtpl:539
		qw422016.N().D(p.RandomNumber(1, 9))
//line templates/page.qtpl:539
		qw422016.N().S(`</span>
                    </div>
                </li>
                `)
//line templates/page.qtpl:542
	}
//line templates/page.qtpl:542
	qw422016.N().S(`
            </ul>
        </div>
    </div>

    <div class="`)
//line templates/page.qtpl:547
	qw422016.E().S(p.Cls("App_SpreadBox"))
//line templates/page.qtpl:547
	qw422016.N().S(`">
        <div class="`)
//line templates/page.qtpl:548
	qw422016.E().S(p.Cls("App_SpreadTitle"))
//line templates/page.qtpl:548
	qw422016.N().S(`">
            <span>评论</span>
            <div class="`)
//line templates/page.qtpl:550
	qw422016.E().S(p.Cls("icon"))
//line templates/page.qtpl:550
	qw422016.N().S(`"></div>
        </div>
        <div class="`)
//line templates/page.qtpl:552
	qw422016.E().S(p.Cls("App-details-comment"))
//line templates/page.qtpl:552
	qw422016.N().S(`">
            <ul>
                `)
//line templates/page.qtpl:554
	for i := 0; i < 10; i++ {
//line templates/page.qtpl:554
		qw422016.N().S(`
                <li class="`)
//line templates/page.qtpl:555
		qw422016.E().S(p.Cls("3ce690"))
//line templates/page.qtpl:555
		qw422016.N().S(`">
                    <table>
                        <tr>
                            <td style="width:230px;">`)
//line templates/page.qtpl:558
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:558
		qw422016.N().S(`</td>
                            <td>`)
//line templates/page.qtpl:559
		qw422016.N().D(p.RandomNumber(1, 59))
//line templates/page.qtpl:559
		qw422016.N().S(`分钟前</td>
                        </tr>
                        <tr>
                            <td colspan="2" style="color:#44423C; text-align:justify;">`)
//line templates/page.qtpl:562
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:562
		qw422016.N().S(`</td>
                        </tr>
                    </table>
                </li>
                `)
//line templates/page.qtpl:566
	}
//line templates/page.qtpl:566
	qw422016.N().S(`
            </ul>
            <a href="`)
//line templates/page.qtpl:568
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:568
	qw422016.N().S(`">
                <div class="`)
//line templates/page.qtpl:569
	qw422016.E().S(p.Cls("link_more"))
//line templates/page.qtpl:569
	qw422016.N().S(`">`)
//line templates/page.qtpl:569
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:569
	qw422016.N().S(`</div>
            </a>
        </div>
    </div>

    <input data-page-role="`)
//line templates/page.qtpl:574
	qw422016.E().S(p.Cls(""))
//line templates/page.qtpl:574
	qw422016.N().S(`" id="SpreadBox_Open" type="hidden" value="`)
//line templates/page.qtpl:574
	qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:574
	qw422016.N().S(`" />
    <input data-aria-hidden="`)
//line templates/page.qtpl:575
	qw422016.E().S(p.Cls(""))
//line templates/page.qtpl:575
	qw422016.N().S(`" id="SpreadBox_Close" type="hidden" value="`)
//line templates/page.qtpl:575
	qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:575
	qw422016.N().S(`" />

    <div class="`)
//line templates/page.qtpl:577
	qw422016.E().S(p.Cls("footer"))
//line templates/page.qtpl:577
	qw422016.N().S(`">
        <div class="`)
//line templates/page.qtpl:578
	qw422016.E().S(p.Cls("wrap"))
//line templates/page.qtpl:578
	qw422016.N().S(`">
            <div class="`)
//line templates/page.qtpl:579
	qw422016.E().S(p.Cls("bottomText"))
//line templates/page.qtpl:579
	qw422016.N().S(`">
                <a href="`)
//line templates/page.qtpl:580
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:580
	qw422016.N().S(`" rel="nofollow">关于我们</a>|
                <a href="`)
//line templates/page.qtpl:581
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:581
	qw422016.N().S(`" rel="nofollow">意见反馈</a>|
                <a href="`)
//line templates/page.qtpl:582
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:582
	qw422016.N().S(`" rel="nofollow">版权声明</a>|
                <a href="`)
//line templates/page.qtpl:583
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:583
	qw422016.N().S(`" rel="nofollow">合作伙伴</a>|
                <a href="`)
//line templates/page.qtpl:584
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:584
	qw422016.N().S(`" rel="nofollow">友情连接</a>|
                <a href="`)
//line templates/page.qtpl:585
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:585
	qw422016.N().S(`" rel="nofollow">联系我们</a>|
                <a href="`)
//line templates/page.qtpl:586
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:586
	qw422016.N().S(`">网站地图</a>
            </div>
            <span>copyright 2022-2024 3673安卓网.All Right Reserved</span>
        </div>
    </div>

    <script>
    var detail = {
        'sid': `)
//line templates/page.qtpl:594
	qw422016.N().D(p.RandomNumber(10000, 99999))
//line templates/page.qtpl:594
	qw422016.N().S(`,
        'sname': "`)
//line templates/page.qtpl:595
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:595
	qw422016.N().S(`",
        'cname': "冒险解谜",
        'crid': `)
//line templates/page.qtpl:597
	qw422016.N().D(p.RandomNumber(1, 10))
//line templates/page.qtpl:597
	qw422016.N().S(`,
        'cid': `)
//line templates/page.qtpl:598
	qw422016.N().D(p.RandomNumber(10, 99))
//line templates/page.qtpl:598
	qw422016.N().S(`
    };
    var _webInfo = {};
    _webInfo = {
        Username: "`)
//line templates/page.qtpl:602
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:602
	qw422016.N().S(`",
        Type: "0",
        DateTime: "`)
//line templates/page.qtpl:604
	qw422016.E().S(p.Now())
//line templates/page.qtpl:604
	qw422016.N().S(`",
        Id: "`)
//line templates/page.qtpl:605
	qw422016.N().D(p.RandomNumber(10000, 99999))
//line templates/page.qtpl:605
	qw422016.N().S(`"
    };
    </script>

    <div id="qrcode1" style="display:none;" title="`)
//line templates/page.qtpl:609
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:609
	qw422016.N().S(`">
        <canvas width="110" height="110" style="display: none;"></canvas>
        <img src="`)
//line templates/page.qtpl:611
	qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:611
	qw422016.N().S(`" style="display: block;" />
    </div>

    <div class="`)
//line templates/page.qtpl:614
	qw422016.E().S(p.Cls("feedBack"))
//line templates/page.qtpl:614
	qw422016.N().S(`">
        <div class="`)
//line templates/page.qtpl:615
	qw422016.E().S(p.Cls("feBaBox"))
//line templates/page.qtpl:615
	qw422016.N().S(`">
            <div class="`)
//line templates/page.qtpl:616
	qw422016.E().S(p.Cls("feBaClose"))
//line templates/page.qtpl:616
	qw422016.N().S(`"><i class="`)
//line templates/page.qtpl:616
	qw422016.E().S(p.Cls("ico"))
//line templates/page.qtpl:616
	qw422016.N().S(`"></i></div>
            <div class="`)
//line templates/page.qtpl:617
	qw422016.E().S(p.Cls("feHead"))
//line templates/page.qtpl:617
	qw422016.N().S(`">用户反馈</div>
            <div class="`)
//line templates/page.qtpl:618
	qw422016.E().S(p.Cls("feBack"))
//line templates/page.qtpl:618
	qw422016.N().S(`">
                <p>反馈原因</p>
                <div class="`)
//line templates/page.qtpl:620
	qw422016.E().S(p.Cls("info"))
//line templates/page.qtpl:620
	qw422016.N().S(`">
                    <div class="`)
//line templates/page.qtpl:621
	qw422016.E().S(p.Cls("checkbox"))
//line templates/page.qtpl:621
	qw422016.N().S(`">
                        <input type="checkbox" id="checkbox1" name="fklb" value="有色情、暴力、反动等不良内容" />
                        <label for="checkbox1">有色情、暴力、反动等不良内容</label>
                    </div>
                    <div class="`)
//line templates/page.qtpl:625
	qw422016.E().S(p.Cls("checkbox"))
//line templates/page.qtpl:625
	qw422016.N().S(`">
                        <input type="checkbox" id="checkbox2" name="fklb" value="有抄袭、侵权嫌疑" />
                        <label for="checkbox2">有抄袭、侵权嫌疑</label>
                    </div>
                    <div class="`)
//line templates/page.qtpl:629
	qw422016.E().S(p.Cls("checkbox"))
//line templates/page.qtpl:629
	qw422016.N().S(`">
                        <input type="checkbox" id="checkbox3" name="fklb" value="广告很多、含有不良插件" />
                        <label for="checkbox3">广告很多、含有不良插件</label>
                    </div>
                    <div class="`)
//line templates/page.qtpl:633
	qw422016.E().S(p.Cls("checkbox"))
//line templates/page.qtpl:633
	qw422016.N().S(`">
                        <input type="checkbox" id="checkbox4" name="fklb" value="无法正常安装或进入游戏" />
                        <label for="checkbox4">无法正常安装或进入游戏</label>
                    </div>
                </div>
                <p>其他原因</p>
                <textarea name="remake" placeholder="请输入补充说明"></textarea>
            </div>
            <div class="`)
//line templates/page.qtpl:641
	qw422016.E().S(p.Cls("h20"))
//line templates/page.qtpl:641
	qw422016.N().S(`"></div>
            <div class="`)
//line templates/page.qtpl:642
	qw422016.E().S(p.Cls("telBox"))
//line templates/page.qtpl:642
	qw422016.N().S(`">
                <span>联系方式</span>
                <input type="tel" name="tel" placeholder="请输入邮箱" />
            </div>
            <div class="`)
//line templates/page.qtpl:646
	qw422016.E().S(p.Cls("feSubmit"))
//line templates/page.qtpl:646
	qw422016.N().S(`">
                <input type="button" class="`)
//line templates/page.qtpl:647
	qw422016.E().S(p.Cls("submit"))
//line templates/page.qtpl:647
	qw422016.N().S(`" name="submit" value="提交反馈" />
            </div>
        </div>
    </div>

    <script type="text/javascript" src="/static/js/comment.js"></script>
    <script type="text/javascript" src="/static/js/footer.js"></script>

    <script type="application/ld+json">{
"@context": "http://zhanzhang.baidu.com/contexts/cambrian.jsonld",
"@id": "`)
//line templates/page.qtpl:657
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:657
	qw422016.N().S(`",
"appid": "否",
"title": "`)
//line templates/page.qtpl:659
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:659
	qw422016.N().S(`",
"images": ["`)
//line templates/page.qtpl:660
	qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:660
	qw422016.N().S(`"],
"description": "`)
//line templates/page.qtpl:661
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:661
	qw422016.N().S(`",
"upDate": "`)
//line templates/page.qtpl:662
	qw422016.E().S(p.Now())
//line templates/page.qtpl:662
	qw422016.N().S(`",
"data": {
"WebPage": {
"pcUrl": "`)
//line templates/page.qtpl:665
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:665
	qw422016.N().S(`",
"wapUrl": "`)
//line templates/page.qtpl:666
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:666
	qw422016.N().S(`",
"fromSrc": "3676安卓网"
}
}
}</script>

    <div id="lightboxOverlay" class="`)
//line templates/page.qtpl:672
	qw422016.E().S(p.Cls("lightboxOverlay"))
//line templates/page.qtpl:672
	qw422016.N().S(`" style="display: none;"></div>
    <div id="lightbox" class="`)
//line templates/page.qtpl:673
	qw422016.E().S(p.Cls("lightbox"))
//line templates/page.qtpl:673
	qw422016.N().S(`" style="display: none;">
        <div class="`)
//line templates/page.qtpl:674
	qw422016.E().S(p.Cls("lb-outerContainer"))
//line templates/page.qtpl:674
	qw422016.N().S(`">
            <div class="`)
//line templates/page.qtpl:675
	qw422016.E().S(p.Cls("lb-container"))
//line templates/page.qtpl:675
	qw422016.N().S(`">
                <img class="`)
//line templates/page.qtpl:676
	qw422016.E().S(p.Cls("lb-image"))
//line templates/page.qtpl:676
	qw422016.N().S(`" src="`)
//line templates/page.qtpl:676
	qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:676
	qw422016.N().S(`" />
                <div class="`)
//line templates/page.qtpl:677
	qw422016.E().S(p.Cls("lb-nav"))
//line templates/page.qtpl:677
	qw422016.N().S(`">
                    <a class="`)
//line templates/page.qtpl:678
	qw422016.E().S(p.Cls("lb-prev"))
//line templates/page.qtpl:678
	qw422016.N().S(`" href="`)
//line templates/page.qtpl:678
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:678
	qw422016.N().S(`"></a>
                    <a class="`)
//line templates/page.qtpl:679
	qw422016.E().S(p.Cls("lb-next"))
//line templates/page.qtpl:679
	qw422016.N().S(`" href="`)
//line templates/page.qtpl:679
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:679
	qw422016.N().S(`"></a>
                </div>
            </div>
        </div>
        <div class="`)
//line templates/page.qtpl:683
	qw422016.E().S(p.Cls("lb-dataContainer"))
//line templates/page.qtpl:683
	qw422016.N().S(`">
            <div class="`)
//line templates/page.qtpl:684
	qw422016.E().S(p.Cls("lb-data"))
//line templates/page.qtpl:684
	qw422016.N().S(`">
                <div class="`)
//line templates/page.qtpl:685
	qw422016.E().S(p.Cls("lb-details"))
//line templates/page.qtpl:685
	qw422016.N().S(`">
                    <span class="`)
//line templates/page.qtpl:686
	qw422016.E().S(p.Cls("lb-caption"))
//line templates/page.qtpl:686
	qw422016.N().S(`"></span>
                    <span class="`)
//line templates/page.qtpl:687
	qw422016.E().S(p.Cls("lb-number"))
//line templates/page.qtpl:687
	qw422016.N().S(`"></span>
                </div>
                <div class="`)
//line templates/page.qtpl:689
	qw422016.E().S(p.Cls("lb-closeContainer"))
//line templates/page.qtpl:689
	qw422016.N().S(`">
                    <a class="`)
//line templates/page.qtpl:690
	qw422016.E().S(p.Cls("lb-close"))
//line templates/page.qtpl:690
	qw422016.N().S(`"></a>
                </div>
            </div>
        </div>
    </div>

    <div id="yyh-bottom" class="`)
//line templates/page.qtpl:696
	qw422016.E().S(p.Cls("yyh-bottom"))
//line templates/page.qtpl:696
	qw422016.N().S(`" style="display: none;">
        <a href="`)
//line templates/page.qtpl:697
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:697
	qw422016.N().S(`">
            <div class="`)
//line templates/page.qtpl:698
	qw422016.E().S(p.Cls("left"))
//line templates/page.qtpl:698
	qw422016.N().S(`">
                <img class="`)
//line templates/page.qtpl:699
	qw422016.E().S(p.Cls("img"))
//line templates/page.qtpl:699
	qw422016.N().S(`" alt="" src="/static/images/close_black.png" />
            </div>
            <div class="`)
//line templates/page.qtpl:701
	qw422016.E().S(p.Cls("middle"))
//line templates/page.qtpl:701
	qw422016.N().S(`">
                <p class="`)
//line templates/page.qtpl:702
	qw422016.E().S(p.Cls("one"))
//line templates/page.qtpl:702
	qw422016.N().S(`">`)
//line templates/page.qtpl:702
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:702
	qw422016.N().S(`</p>
                <p class="`)
//line templates/page.qtpl:703
	qw422016.E().S(p.Cls("two"))
//line templates/page.qtpl:703
	qw422016.N().S(`">`)
//line templates/page.qtpl:703
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:703
	qw422016.N().S(`</p>
            </div>
            <p class="`)
//line templates/page.qtpl:705
	qw422016.E().S(p.Cls("right"))
//line templates/page.qtpl:705
	qw422016.N().S(`">
                <span class="`)
//line templates/page.qtpl:706
	qw422016.E().S(p.Cls("freedownload"))
//line templates/page.qtpl:706
	qw422016.N().S(`">下载</span>
            </p>
        </a>
        <span id="m-close" class="`)
//line templates/page.qtpl:709
	qw422016.E().S(p.Cls("m-close"))
//line templates/page.qtpl:709
	qw422016.N().S(`">
            <img alt="" src="`)
//line templates/page.qtpl:710
	qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:710
	qw422016.N().S(`" />
        </span>
    </div>

    <header class="`)
//line templates/page.qtpl:714
	qw422016.E().S(p.Cls("Header"))
//line templates/page.qtpl:714
	qw422016.N().S(`">
        <div class="`)
//line templates/page.qtpl:715
	qw422016.E().S(p.Cls("Top"))
//line templates/page.qtpl:715
	qw422016.N().S(`">
            <a href="`)
//line templates/page.qtpl:716
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:716
	qw422016.N().S(`" class="`)
//line templates/page.qtpl:716
	qw422016.E().S(p.Cls("logo"))
//line templates/page.qtpl:716
	qw422016.N().S(`">
                <img alt="" class="`)
//line templates/page.qtpl:717
	qw422016.E().S(p.Cls("logo_img"))
//line templates/page.qtpl:717
	qw422016.N().S(`" src="/static/temp/heqishengcai2024/logo2.png" />
            </a>
            <div class="`)
//line templates/page.qtpl:719
	qw422016.E().S(p.Cls("SearchBox"))
//line templates/page.qtpl:719
	qw422016.N().S(`">
                <form action="/search/" method="GET">
                    <div class="`)
//line templates/page.qtpl:721
	qw422016.E().S(p.Cls("Search_Input"))
//line templates/page.qtpl:721
	qw422016.N().S(`">
                        <input type="text" id="keyword" class="`)
//line templates/page.qtpl:722
	qw422016.E().S(p.Cls("s_input"))
//line templates/page.qtpl:722
	qw422016.N().S(`" value="" />
                    </div>
                    <input type="image" class="`)
//line templates/page.qtpl:724
	qw422016.E().S(p.Cls("i-input"))
//line templates/page.qtpl:724
	qw422016.N().S(`" src="`)
//line templates/page.qtpl:724
	qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:724
	qw422016.N().S(`" />
                </form>
            </div>
        </div>
    </header>

    <div class="`)
//line templates/page.qtpl:730
	qw422016.E().S(p.Cls("main"))
//line templates/page.qtpl:730
	qw422016.N().S(`">
        <div class="`)
//line templates/page.qtpl:731
	qw422016.E().S(p.Cls("mainpage"))
//line templates/page.qtpl:731
	qw422016.N().S(`">
            <div class="`)
//line templates/page.qtpl:732
	qw422016.E().S(p.Cls("breadcrumb"))
//line templates/page.qtpl:732
	qw422016.N().S(`">
                <a href="`)
//line templates/page.qtpl:733
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:733
	qw422016.N().S(`">首页</a>
                &gt;
                <a href="`)
//line templates/page.qtpl:735
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:735
	qw422016.N().S(`">`)
//line templates/page.qtpl:735
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:735
	qw422016.N().S(`</a>
                &gt;
                <a href="`)
//line templates/page.qtpl:737
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:737
	qw422016.N().S(`">`)
//line templates/page.qtpl:737
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:737
	qw422016.N().S(`</a>
            </div>

            <div class="`)
//line templates/page.qtpl:740
	qw422016.E().S(p.Cls("AppBox"))
//line templates/page.qtpl:740
	qw422016.N().S(`">
                <div class="`)
//line templates/page.qtpl:741
	qw422016.E().S(p.Cls("App-details"))
//line templates/page.qtpl:741
	qw422016.N().S(`">
                    <img class="`)
//line templates/page.qtpl:742
	qw422016.E().S(p.Cls("icon"))
//line templates/page.qtpl:742
	qw422016.N().S(`" height="51px" width="51px" alt="`)
//line templates/page.qtpl:742
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:742
	qw422016.N().S(`" src="`)
//line templates/page.qtpl:742
	qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:742
	qw422016.N().S(`" />
                    <div class="`)
//line templates/page.qtpl:743
	qw422016.E().S(p.Cls("App-details-det"))
//line templates/page.qtpl:743
	qw422016.N().S(`">
                        <div class="`)
//line templates/page.qtpl:744
	qw422016.E().S(p.Cls("app-details-appname"))
//line templates/page.qtpl:744
	qw422016.N().S(`">
                            <h1>`)
//line templates/page.qtpl:745
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:745
	qw422016.N().S(`</h1>
                        </div>
                        <div class="`)
//line templates/page.qtpl:747
	qw422016.E().S(p.Cls("app-details-appdes"))
//line templates/page.qtpl:747
	qw422016.N().S(`">
                            <h3>「活动」首次登录送`)
//line templates/page.qtpl:748
	qw422016.N().D(p.RandomNumber(50, 200))
//line templates/page.qtpl:748
	qw422016.N().S(`元红包</h3>
                        </div>
                        <div class="`)
//line templates/page.qtpl:750
	qw422016.E().S(p.Cls("app-details-appinfo"))
//line templates/page.qtpl:750
	qw422016.N().S(`">
                            <div>`)
//line templates/page.qtpl:751
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:751
	qw422016.N().S(`</div>
                            <div>`)
//line templates/page.qtpl:752
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:752
	qw422016.N().S(`</div>
                        </div>
                    </div>
                </div>
                <div class="`)
//line templates/page.qtpl:756
	qw422016.E().S(p.Cls("App-display-a"))
//line templates/page.qtpl:756
	qw422016.N().S(`">
                    <div class="`)
//line templates/page.qtpl:757
	qw422016.E().S(p.Cls("download_btn_col"))
//line templates/page.qtpl:757
	qw422016.N().S(`">
                        <a class="`)
//line templates/page.qtpl:758
	qw422016.E().S(p.Cls("normal-down-btn"))
//line templates/page.qtpl:758
	qw422016.N().S(`" href="`)
//line templates/page.qtpl:758
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:758
	qw422016.N().S(`">下载APK</a>
                        <a class="`)
//line templates/page.qtpl:759
	qw422016.E().S(p.Cls("high-speed-down-btn"))
//line templates/page.qtpl:759
	qw422016.N().S(`" href="`)
//line templates/page.qtpl:759
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:759
	qw422016.N().S(`">高速下载</a>
                    </div>
                    <div class="`)
//line templates/page.qtpl:761
	qw422016.E().S(p.Cls("b-text"))
//line templates/page.qtpl:761
	qw422016.N().S(`">
                        <span class="`)
//line templates/page.qtpl:762
	qw422016.E().S(p.Cls("span"))
//line templates/page.qtpl:762
	qw422016.N().S(`">下载安装你想要的应用 更方便 更快捷 发现更多</span>
                    </div>
                </div>
                <div class="`)
//line templates/page.qtpl:765
	qw422016.E().S(p.Cls("App_Hots"))
//line templates/page.qtpl:765
	qw422016.N().S(`">
                    <div>
                        <div class="`)
//line templates/page.qtpl:767
	qw422016.E().S(p.Cls("fr"))
//line templates/page.qtpl:767
	qw422016.N().S(`">
                            <img alt="喜欢" src="/static/images/icon_03.png" />
                            <span>`)
//line templates/page.qtpl:769
	qw422016.N().D(p.RandomNumber(30, 90))
//line templates/page.qtpl:769
	qw422016.N().S(`%好评(`)
//line templates/page.qtpl:769
	qw422016.N().D(p.RandomNumber(10, 100))
//line templates/page.qtpl:769
	qw422016.N().S(`人)</span>
                        </div>
                    </div>
                    <div>
                        <div class="`)
//line templates/page.qtpl:773
	qw422016.E().S(p.Cls("fl"))
//line templates/page.qtpl:773
	qw422016.N().S(`">
                            <img alt="评论" src="/static/images/icon_04.png" />
                            <span>`)
//line templates/page.qtpl:775
	qw422016.N().D(p.RandomNumber(10, 200))
//line templates/page.qtpl:775
	qw422016.N().S(`</span>
                        </div>
                    </div>
                </div>
                <div class="`)
//line templates/page.qtpl:779
	qw422016.E().S(p.Cls("img"))
//line templates/page.qtpl:779
	qw422016.N().S(`">
                    <div class="`)
//line templates/page.qtpl:780
	qw422016.E().S(p.Cls("App_ImgBox"))
//line templates/page.qtpl:780
	qw422016.N().S(`">
                        `)
//line templates/page.qtpl:781
	for i := 0; i < 5; i++ {
//line templates/page.qtpl:781
		qw422016.N().S(`
                        <img alt="`)
//line templates/page.qtpl:782
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:782
		qw422016.N().S(`截图`)
//line templates/page.qtpl:782
		qw422016.N().D(i)
//line templates/page.qtpl:782
		qw422016.N().S(`" src="`)
//line templates/page.qtpl:782
		qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:782
		qw422016.N().S(`" />
                        `)
//line templates/page.qtpl:783
	}
//line templates/page.qtpl:783
	qw422016.N().S(`
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="`)
//line templates/page.qtpl:790
	qw422016.E().S(p.Cls("main"))
//line templates/page.qtpl:790
	qw422016.N().S(`">
        <div class="`)
//line templates/page.qtpl:791
	qw422016.E().S(p.Cls("mainpage mbt_27"))
//line templates/page.qtpl:791
	qw422016.N().S(`">
            <section class="`)
//line templates/page.qtpl:792
	qw422016.E().S(p.Cls("ClassifyBox"))
//line templates/page.qtpl:792
	qw422016.N().S(`">
                <ul>
                    <li class="`)
//line templates/page.qtpl:794
	qw422016.E().S(p.Cls("Classify_Checked"))
//line templates/page.qtpl:794
	qw422016.N().S(`"><a href="`)
//line templates/page.qtpl:794
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:794
	qw422016.N().S(`">`)
//line templates/page.qtpl:794
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:794
	qw422016.N().S(`</a></li>
                    `)
//line templates/page.qtpl:795
	for i := 0; i < 20; i++ {
//line templates/page.qtpl:795
		qw422016.N().S(`
                    <li data-is-active="`)
//line templates/page.qtpl:796
		qw422016.E().S(p.Cls(""))
//line templates/page.qtpl:796
		qw422016.N().S(`">
                        <a href="`)
//line templates/page.qtpl:797
		qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:797
		qw422016.N().S(`">`)
//line templates/page.qtpl:797
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:797
		qw422016.N().S(`</a>
                    </li>
                    `)
//line templates/page.qtpl:799
	}
//line templates/page.qtpl:799
	qw422016.N().S(`
                </ul>
            </section>

            <ul class="`)
//line templates/page.qtpl:803
	qw422016.E().S(p.Cls("list_con"))
//line templates/page.qtpl:803
	qw422016.N().S(`">
                `)
//line templates/page.qtpl:804
	for i := 0; i < 132; i++ {
//line templates/page.qtpl:804
		qw422016.N().S(`
                <li class="`)
//line templates/page.qtpl:805
		qw422016.E().S(p.Cls("app-list-con"))
//line templates/page.qtpl:805
		qw422016.N().S(`">
                    <a href="`)
//line templates/page.qtpl:806
		qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:806
		qw422016.N().S(`">
                        <img class="`)
//line templates/page.qtpl:807
		qw422016.E().S(p.Cls("app-list-img"))
//line templates/page.qtpl:807
		qw422016.N().S(`" alt="`)
//line templates/page.qtpl:807
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:807
		qw422016.N().S(`" title="`)
//line templates/page.qtpl:807
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:807
		qw422016.N().S(`">
                    </a>
                    <div class="`)
//line templates/page.qtpl:809
		qw422016.E().S(p.Cls("app-list-details"))
//line templates/page.qtpl:809
		qw422016.N().S(`">
                        <div class="`)
//line templates/page.qtpl:810
		qw422016.E().S(p.Cls("app-list-name"))
//line templates/page.qtpl:810
		qw422016.N().S(`">
                            <h2><a href="`)
//line templates/page.qtpl:811
		qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:811
		qw422016.N().S(`">`)
//line templates/page.qtpl:811
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:811
		qw422016.N().S(`</a></h2>
                        </div>
                        <div class="`)
//line templates/page.qtpl:813
		qw422016.E().S(p.Cls("app-list-des"))
//line templates/page.qtpl:813
		qw422016.N().S(`">
                            <h3>`)
//line templates/page.qtpl:814
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:814
		qw422016.N().S(`</h3>
                        </div>
                        <div class="`)
//line templates/page.qtpl:816
		qw422016.E().S(p.Cls("app-list-info"))
//line templates/page.qtpl:816
		qw422016.N().S(`">
                            <div>`)
//line templates/page.qtpl:817
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:817
		qw422016.N().S(`</div>
                            <div>`)
//line templates/page.qtpl:818
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:818
		qw422016.N().S(`</div>
                        </div>
                    </div>
                    <div class="`)
//line templates/page.qtpl:821
		qw422016.E().S(p.Cls("app-list-download"))
//line templates/page.qtpl:821
		qw422016.N().S(`">
                        <a class="`)
//line templates/page.qtpl:822
		qw422016.E().S(p.Cls("detail"))
//line templates/page.qtpl:822
		qw422016.N().S(`" href="`)
//line templates/page.qtpl:822
		qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:822
		qw422016.N().S(`">`)
//line templates/page.qtpl:822
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:822
		qw422016.N().S(`</a>
                    </div>
                </li>
                `)
//line templates/page.qtpl:825
	}
//line templates/page.qtpl:825
	qw422016.N().S(`
            </ul>
        </div>
    </div>

    <div class="`)
//line templates/page.qtpl:830
	qw422016.E().S(p.Cls("App-everybody-dl"))
//line templates/page.qtpl:830
	qw422016.N().S(`">
        <h3 class="`)
//line templates/page.qtpl:831
	qw422016.E().S(p.Cls("title"))
//line templates/page.qtpl:831
	qw422016.N().S(`">`)
//line templates/page.qtpl:831
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:831
	qw422016.N().S(`</h3>
        <ul class="`)
//line templates/page.qtpl:832
	qw422016.E().S(p.Cls("App-ul fix"))
//line templates/page.qtpl:832
	qw422016.N().S(`" style="width: 100%; overflow: hidden;">
            `)
//line templates/page.qtpl:833
	for i := 0; i < 1271; i++ {
//line templates/page.qtpl:833
		qw422016.N().S(`
            <li class="`)
//line templates/page.qtpl:834
		qw422016.E().S(p.Cls("li fix"))
//line templates/page.qtpl:834
		qw422016.N().S(`">
                <a href="`)
//line templates/page.qtpl:835
		qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:835
		qw422016.N().S(`">
                    <div class="`)
//line templates/page.qtpl:836
		qw422016.E().S(p.Cls("img"))
//line templates/page.qtpl:836
		qw422016.N().S(`">
                        `)
//line templates/page.qtpl:837
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:837
		qw422016.N().S(`
                    </div>
                </a>
                <div class="`)
//line templates/page.qtpl:840
		qw422016.E().S(p.Cls("right"))
//line templates/page.qtpl:840
		qw422016.N().S(`" style="padding-left: 0;">
                    <p class="`)
//line templates/page.qtpl:841
		qw422016.E().S(p.Cls("App-name"))
//line templates/page.qtpl:841
		qw422016.N().S(`">`)
//line templates/page.qtpl:841
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:841
		qw422016.N().S(`</p>
                    </a>
                </div>
            </li>
            `)
//line templates/page.qtpl:845
	}
//line templates/page.qtpl:845
	qw422016.N().S(`
        </ul>
    </div>

    <div class="`)
//line templates/page.qtpl:849
	qw422016.E().S(p.Cls("App_SpreadContent"))
//line templates/page.qtpl:849
	qw422016.N().S(`">
        <ul class="`)
//line templates/page.qtpl:850
	qw422016.E().S(p.Cls("Applicati****_list list_con"))
//line templates/page.qtpl:850
	qw422016.N().S(`">
            <li class="`)
//line templates/page.qtpl:851
	qw422016.E().S(p.Cls("Application_content"))
//line templates/page.qtpl:851
	qw422016.N().S(`">
                <div class="`)
//line templates/page.qtpl:852
	qw422016.E().S(p.Cls("Application_img_set ml0"))
//line templates/page.qtpl:852
	qw422016.N().S(`">
                    <a href="`)
//line templates/page.qtpl:853
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:853
	qw422016.N().S(`">
                        <img class="`)
//line templates/page.qtpl:854
	qw422016.E().S(p.Cls("small"))
//line templates/page.qtpl:854
	qw422016.N().S(`" src="`)
//line templates/page.qtpl:854
	qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:854
	qw422016.N().S(`" />
                    </a>
                    <a href="`)
//line templates/page.qtpl:856
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:856
	qw422016.N().S(`">
                        <img class="`)
//line templates/page.qtpl:857
	qw422016.E().S(p.Cls("middle"))
//line templates/page.qtpl:857
	qw422016.N().S(`" src="`)
//line templates/page.qtpl:857
	qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:857
	qw422016.N().S(`" />
                    </a>
                    <a href="`)
//line templates/page.qtpl:859
	qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:859
	qw422016.N().S(`">
                        <img class="`)
//line templates/page.qtpl:860
	qw422016.E().S(p.Cls("bigger"))
//line templates/page.qtpl:860
	qw422016.N().S(`" src="`)
//line templates/page.qtpl:860
	qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:860
	qw422016.N().S(`" />
                    </a>
                </div>
            </li>
            `)
//line templates/page.qtpl:864
	for i := 0; i < 80; i++ {
//line templates/page.qtpl:864
		qw422016.N().S(`
            <li class="`)
//line templates/page.qtpl:865
		qw422016.E().S(p.Cls("WYpg Application_content"))
//line templates/page.qtpl:865
		qw422016.N().S(`">
                <div class="`)
//line templates/page.qtpl:866
		qw422016.E().S(p.Cls("Application_img_set ml0"))
//line templates/page.qtpl:866
		qw422016.N().S(`">
                    <a href="`)
//line templates/page.qtpl:867
		qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:867
		qw422016.N().S(`">
                        <img class="`)
//line templates/page.qtpl:868
		qw422016.E().S(p.Cls("small"))
//line templates/page.qtpl:868
		qw422016.N().S(`" src="`)
//line templates/page.qtpl:868
		qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:868
		qw422016.N().S(`" />
                    </a>
                    <a href="`)
//line templates/page.qtpl:870
		qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:870
		qw422016.N().S(`">
                        <img class="`)
//line templates/page.qtpl:871
		qw422016.E().S(p.Cls("middle"))
//line templates/page.qtpl:871
		qw422016.N().S(`" src="`)
//line templates/page.qtpl:871
		qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:871
		qw422016.N().S(`" />
                    </a>
                    <a href="`)
//line templates/page.qtpl:873
		qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:873
		qw422016.N().S(`">
                        <img class="`)
//line templates/page.qtpl:874
		qw422016.E().S(p.Cls("bigger"))
//line templates/page.qtpl:874
		qw422016.N().S(`" src="`)
//line templates/page.qtpl:874
		qw422016.E().S(p.RandomImage())
//line templates/page.qtpl:874
		qw422016.N().S(`" />
                    </a>
                </div>
                <a href="`)
//line templates/page.qtpl:877
		qw422016.E().S(p.RandomURL())
//line templates/page.qtpl:877
		qw422016.N().S(`">
                    <div class="`)
//line templates/page.qtpl:878
		qw422016.E().S(p.Cls("App"))
//line templates/page.qtpl:878
		qw422016.N().S(`">
                        <div class="`)
//line templates/page.qtpl:879
		qw422016.E().S(p.Cls("App_tit"))
//line templates/page.qtpl:879
		qw422016.N().S(`">`)
//line templates/page.qtpl:879
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:879
		qw422016.N().S(`</div>
                        <div class="`)
//line templates/page.qtpl:880
		qw422016.E().S(p.Cls("App_user"))
//line templates/page.qtpl:880
		qw422016.N().S(`">`)
//line templates/page.qtpl:880
		qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:880
		qw422016.N().S(`</div>
                        <div class="`)
//line templates/page.qtpl:881
		qw422016.E().S(p.Cls("App_oth"))
//line templates/page.qtpl:881
		qw422016.N().S(`">
                            <span>`)
//line templates/page.qtpl:882
		qw422016.N().D(p.RandomNumber(10000, 99999))
//line templates/page.qtpl:882
		qw422016.N().S(`</span>
                            <span>`)
//line templates/page.qtpl:883
		qw422016.N().D(p.RandomNumber(10000, 99999))
//line templates/page.qtpl:883
		qw422016.N().S(`</span>
                            <span>`)
//line templates/page.qtpl:884
		qw422016.E().S(p.Now())
//line templates/page.qtpl:884
		qw422016.N().S(`</span>
                        </div>
                    </div>
                </a>
            </li>
            `)
//line templates/page.qtpl:889
	}
//line templates/page.qtpl:889
	qw422016.N().S(`
        </ul>
    </div>

    <div class="`)
//line templates/page.qtpl:893
	qw422016.E().S(p.Cls("Footer"))
//line templates/page.qtpl:893
	qw422016.N().S(`">
        <div class="`)
//line templates/page.qtpl:894
	qw422016.E().S(p.Cls("Footer-line"))
//line templates/page.qtpl:894
	qw422016.N().S(`"></div>
        <span class="`)
//line templates/page.qtpl:895
	qw422016.E().S(p.Cls("Appchina.com/"))
//line templates/page.qtpl:895
	qw422016.N().S(`">`)
//line templates/page.qtpl:895
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:895
	qw422016.N().S(`-安卓手机网上最贴心的Android软件应用平台!</span>
        <span class="`)
//line templates/page.qtpl:896
	qw422016.E().S(p.Cls("Footer-com"))
//line templates/page.qtpl:896
	qw422016.N().S(`">版权所有：`)
//line templates/page.qtpl:896
	qw422016.N().S(string(p.RandomKeyword()))
//line templates/page.qtpl:896
	qw422016.N().S(`有限公司</span>
        <span class="`)
//line templates/page.qtpl:897
	qw422016.E().S(p.Cls("Footer-com"))
//line templates/page.qtpl:897
	qw422016.N().S(`">备案号：京ICP备44633832号-1</span>
    </div>

</div>

<script type="text/javascript">
    function SetImgBoxWidth() {
        var app_screenshot_list_width = 0;
        $('.App_ImgBox').find('img').each(function () {
            app_screenshot_list_width += $(this).width() + 8;
            app_screenshot_list_width += 5;
        });
        $(".App_ImgBox").css("width", app_screenshot_list_width + 2);
    }
    onload = function () {
        SetImgBoxWidth();
    };
    AdjustElement();
</script>

<script>
    (function () {
        var bp = document.createElement('script');
        var curProtocol = window.location.protocol.split(':')[0];
        if (curProtocol === 'https') {
            bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
        }
        else {
            bp.src = 'http://push.zhanzhang.baidu.com/push.js';
        }
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(bp, s);
    })();
</script>
`)
//line templates/page.qtpl:931
	qw422016.N().S(p.BaiduPushJS)
//line templates/page.qtpl:931
	qw422016.N().S(`
</body>

</html>
`)
//line templates/page.qtpl:935
}

//line templates/page.qtpl:935
func (p *PageParams) WriteRender(qq422016 qtio422016.Writer) {
//line templates/page.qtpl:935
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/page.qtpl:935
	p.StreamRender(qw422016)
//line templates/page.qtpl:935
	qt422016.ReleaseWriter(qw422016)
//line templates/page.qtpl:935
}

//line templates/page.qtpl:935
func (p *PageParams) Render() string {
//line templates/page.qtpl:935
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/page.qtpl:935
	p.WriteRender(qb422016)
//line templates/page.qtpl:935
	qs422016 := string(qb422016.B)
//line templates/page.qtpl:935
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/page.qtpl:935
	return qs422016
//line templates/page.qtpl:935
}
